server:
  port: 9999 # 端口: 8080
spring:
  gobrs:
    async:
      #      enable: false
      rules:
        - name: "general"
          content: "AService->BService->FService->GService->HService;EService->CService;AService"
        - name: "anyConditionGeneral"
          content: "AServiceCondition,BServiceCondition,CServiceCondition->DServiceCondition"
        - name: "anyConditionRule"
          content: "AServiceCondition,BServiceCondition,CServiceCondition->DServiceCondition:anyCondition"
        - name: "anyConditionRuleAppend"
          content: "AServiceCondition,BServiceCondition,CServiceCondition->DServiceCondition:anyCondition->EServiceCondition"

