server:
  port: 8888 # 端口: 8080
spring:
  gobrs:
    async:
      rules: '[{name: "test", content: "BService,CService,FService->AService; BService->FService,GService;"}]'
      task-interrupt: false #局部异常是否打断主流程
