server:
  port: 8888
spring:
  gobrs:
    async:
      rules: '[{name: "test", content: "AService->CService->EService->GService; BService->DService->FService->GService->HService;"}]'
      task-interrupt: true #局部异常是否打断主流程
