server:
  port: 8888
spring:
  gobrs:
    async:
      rules: '[{name: "test", content: "AService->BService->CService->EService->DService;EService->DService"}]'
      task-interrupt: false #局部异常是否打断主流程